# Generated by Django 4.2.19 on 2025-04-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_chatroom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="chatlog",
            index=models.Index(
                fields=["chatroom", "timestamp"], name="chatbot_cha_chatroo_6d2757_idx"
            ),
        ),
    ]
