# Generated by Django 4.2.19 on 2025-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_social",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="social_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
