# Generated by Django 4.2.19 on 2025-03-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_social_user_social_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit",
            field=models.IntegerField(default=0),
        ),
    ]
